import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import Add from "@/components/home/Add";
import Navbar from "@/components/ui/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased w-full h-[100vh] flex flex-col`}>
        <Add />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
